//
// AUTO-GENERATED by build hook.  Do not edit or commit
//
#define AG_BUNDLEMANAGER_BUILD_HASH     @"6e74ce3e694c7ce2d98634a2c48b45fbd92aca3d"
#define AG_BUNDLEMANAGER_BUILD_TAG      @"4.0.1"
#define AG_BUNDLEMANAGER_BUILD_DATE     @"Thu May 26 10:36:42 EDT 2016"
