//
// AUTO-GENERATED by build hook.  Do not edit or commit
//
#define AG_SDK_BUILD_HASH   @"873a9c782fa880079b0ca2b320ffe25820876d0a"
#define AG_SDK_BUILD_TAG    @"4.0.1"
#define AG_SDK_BUILD_DATE   @"Thu May 26 10:51:40 EDT 2016"
